### ISSUE TITLE
Broken Codacy badge link in README

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx-motr-galois#12]
Hi, 

The Codacy badge link had broken and it show broken image in GitHub page.

**Comment by sanjognaik** [comment]
Fixed Codacy badge link.

**Comment by cortx-admin** [comment]
> Sanjog Vikram Naik commented in Jira Server:

Create [PR-16|https://github.com/Seagate/cortx-motr-galois/pull/16].

**Comment by cortx-admin** [comment]
> Sanjog Vikram Naik commented in Jira Server:

PR is merged

**Comment by cortx-admin** [comment]
> Sanjog Vikram Naik commented in Jira Server:

Codacy badge is seen properly on the repo.
